apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-alerts
  namespace: kube-system
spec:
  groups:
  - name: resource-usage
    rules:
    - alert: HighCPUUsage
      expr: (sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) / sum(kube_pod_container_resource_requests{resource="cpu"}) by (pod)) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "Pod {{ $labels.pod }} is using more than 80% of its requested CPU for more than 5 minutes."
    - alert: HighMemoryUsage
      expr: (sum(container_memory_usage_bytes) by (pod) / sum(kube_pod_container_resource_requests{resource="memory"}) by (pod)) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Memory usage detected"
        description: "Pod {{ $labels.pod }} is using more than 80% of its requested memory for more than 5 minutes."
