name: Dockerfile CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: goku0713/ubuntu2204python:${{ github.sha }}
        file: ./Dockerfile

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
  
    - name: Scan Docker image with Trivy
      run: trivy image goku0713/ubuntu2204python:${{ github.sha }}

    #- name: Deploy to Kubernetes
    #  run: |
    #    kubectl apply -f deployment.yaml
    #    kubectl apply -f service.yaml
    #  env:
    #    KUBECONFIG: ${{ secrets.KUBECONFIG }}
