name: Deploy JupyterHub on Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kind cluster
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: v0.27.0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      id: install

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Add JupyterHub Helm repo
      run: |
        # https://github.com/jupyterhub/helm-chart?tab=readme-ov-file https://z2jh.jupyter.org/en/stable/
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
        helm repo update

    - name: Deploy JupyterHub
      run: |
        helm upgrade --install jupyterhub jupyterhub/jupyterhub \
          --namespace jupyterhub \
          --create-namespace \
          --version=4.1.0 \
          --values jupyter-config.yaml

    - name: Wait for JupyterHub to be ready
      run: |
        kubectl wait --for=condition=ready pod --all --timeout=600s -n jupyterhub

    - name: Get JupyterHub URL
      run: |
        echo "JupyterHub URL: http://$(kubectl get svc proxy-public -n jupyterhub -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):$(kubectl get svc proxy-public -n jupyterhub -o jsonpath='{.spec.ports[0].port}')"

    - name: Setup Monitoring
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

        helm upgrade --install prometheus prometheus-community/prometheus --namespace kube-system --create-namespace
        helm upgrade --install grafana grafana/grafana --namespace kube-system --create-namespace --set persistence.enabled=true

        # Wait for prometheus and grafana to be ready
        kubectl wait --for=condition=ready pod --all --timeout=600s -n kube-system

        kubectl apply -f prometheus-alerts.yaml --namespace monitoring
